# Generated by Django 4.2.3 on 2023-07-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_states',
            field=models.CharField(choices=[('W', 'Want to Read'), ('G', 'Reading'), ('R', 'Read')], default='W', max_length=1),
        ),
    ]
