# Generated by Django 4.2.3 on 2023-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_read_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='read_states',
            field=models.CharField(choices=[('Want to Read', 'Want to Read'), ('Reading', 'Reading'), ('Read', 'Read')], default='Want to Read', max_length=12),
        ),
    ]
