# Generated by Django 4.2.3 on 2023-11-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_bio',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
