# Generated by Django 4.2.3 on 2023-11-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_userprofile_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='icons8-person-48.png', upload_to=''),
        ),
    ]
