# Generated by Django 4.2.3 on 2023-11-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='books_currently_reading',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='books_read',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='books_want_to_read',
        ),
    ]
