# Generated by Django 4.2.3 on 2023-11-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_remove_userprofile_books_currently_reading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='book',
        ),
    ]
