# Generated by Django 4.2.3 on 2023-11-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
