# Generated by Django 4.2.3 on 2023-11-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_books_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_id',
            new_name='google_book_id',
        ),
    ]
