# Generated by Django 4.2.3 on 2023-11-14 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_rename_google_book_id_books_google_books_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_status', models.CharField(choices=[('WANT_TO_READ', 'Want to Read'), ('CURRENTLY_READING', 'Currently Reading'), ('ALREADY_READ', 'Already Read')], default='WANT_TO_READ', max_length=20)),
                ('reading_progress', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
