# Generated by Django 4.2.3 on 2023-11-18 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='object_id',
        ),
        migrations.AddField(
            model_name='feed',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
        migrations.AddField(
            model_name='feed',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rate'),
        ),
    ]
