# Generated by Django 4.2.3 on 2023-12-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_like_unique_together_remove_like_bookmark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
